name: '`brew test-bot` result summary'
description: Output the logs stored at the specified path
inputs:
  workdir:
    description: Working directory of the result
    required: true
    default: ${{ github.workspace }}
  result_path:
    description: Path to the result (relative to workdir)
    required: true
    default: bottles/steps_output.txt
  step_name:
    description: Heading to use in GitHub step summary
    required: true
    default: '`brew test-bot` output'
  collapse:
    description: Whether to collapse the output
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - run: |
        if [[ -f "$GITHUB_STEP_SUMMARY" ]] &&
           [[ ! -w "$GITHUB_STEP_SUMMARY" ]]
        then
          sudo chown "$(whoami)" "$GITHUB_STEP_SUMMARY"
        fi

        full_result_path="${{ inputs.workdir }}/${{ inputs.result_path }}"

        [[ -s "$full_result_path" ]] || exit 0

        printf '### ${{ inputs.step_name }}\n' >> "$GITHUB_STEP_SUMMARY"
        "${{ inputs.collapse }}" && printf '\n<details><summary>Details</summary>\n<p>\n\n' >> "$GITHUB_STEP_SUMMARY"
        printf '```\n' >> "$GITHUB_STEP_SUMMARY"
        sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' "$full_result_path" | tee -a "$GITHUB_STEP_SUMMARY"
        printf '\n```\n' >> "$GITHUB_STEP_SUMMARY"
        "${{ inputs.collapse }}" && printf '\n</p>\n</details>\n' >> "$GITHUB_STEP_SUMMARY"

        rm "$full_result_path"
      shell: bash
