name: '`brew test-bot` result summary'
description: Output the logs stored at the specified path
inputs:
  workdir:
    description: Working directory of the result
    required: true
    default: ${{ github.workspace }}
  result_path:
    description: Path to the result (relative to workdir)
    required: true
    default: bottles/steps_output.txt
  step_name:
    description: Heading to use in GitHub step summary
    required: true
    default: '`brew test-bot` output'
  collapse:
    description: Whether to collapse the output
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - run: |
        if [[ -f "$GITHUB_STEP_SUMMARY" ]] &&
           [[ ! -w "$GITHUB_STEP_SUMMARY" ]]
        then
          sudo chown "$(whoami)" "$GITHUB_STEP_SUMMARY"
        fi

        full_result_path="$WORKDIR/$RESULT_PATH"

        [[ -s "$full_result_path" ]] || exit 0

        {
          printf '%s' "### $STEP_NAME\n"
          [[ "$COLLAPSE" != true ]] || printf '%s' '\n<details><summary>Details</summary>\n<p>\n\n'
          printf '%s' '```\n'
          # Remove colours from the output
          sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' "$full_result_path"
          printf '%s' '\n```\n'
          [[ "$COLLAPSE" != true ]] || printf '%s' '\n</p>\n</details>\n'
        } | tee -a "$GITHUB_STEP_SUMMARY"

        rm "$full_result_path"
      shell: /bin/bash -euo pipefail {0}
      env:
        WORKDIR: ${{ inputs.workdir }}
        RESULT_PATH: ${{ inputs.result_path }}
        STEP_NAME: ${{ inputs.step_name }}
        COLLAPSE: ${{ inputs.collapse }}
