name: '`brew test-bot` result summary'
description: Output the logs stored at the specified path
inputs:
  workdir:
    description: Working directory of the result
    required: true
    default: ${{ github.workspace }}
  result_path:
    description: Path to the result (relative to workdir)
    required: false
    default: bottles/steps_output.txt


runs:
  using: composite
  steps:
    - run: |
        touch ${{ inputs.workdir }}/${{ inputs.result_path }}
        cat ${{ inputs.workdir }}/${{ inputs.result_path }}
        rm ${{ inputs.workdir }}/${{ inputs.result_path }}
      shell: bash
