name: Failures summary and bottle result
description: Output the logs of the bottle generation and a summary of all step failures

runs:
  using: composite
  steps:
    - run: |
        touch bottles/steps_output.txt
        cat bottles/steps_output.txt
        rm bottles/steps_output.txt
      shell: bash

    - run: |
        cat bottles/bottle_output.txt
        rm bottles/bottle_output.txt
      shell: bash

