name: '`brew test-bot` result summary'
description: Output the logs stored at the specified path
inputs:
  workdir:
    description: Working directory of the result
    required: true
    default: ${{ github.workspace }}
  result_path:
    description: Path to the result (relative to workdir)
    required: false
    default: bottles/steps_output.txt
  step_name:
    description: Heading to use in GitHub step summary
    required: false
    default: '`brew test-bot` output'

runs:
  using: composite
  steps:
    - run: |
        if [[ -f "$GITHUB_STEP_SUMMARY" ]] &&
           [[ ! -w "$GITHUB_STEP_SUMMARY" ]]
        then
          sudo chown "$(whoami)" "$GITHUB_STEP_SUMMARY"
        fi

        full_result_path="${{ inputs.workdir }}/${{ inputs.result_path }}"

        touch "$path"

        echo '### ${{ inputs.step_name }}' >> "$GITHUB_STEP_SUMMARY"
        printf '```\n' >> "$GITHUB_STEP_SUMMARY"
        tee -a "$GITHUB_STEP_SUMMARY" <"$full_result_path"
        printf '\n```' >> "$GITHUB_STEP_SUMMARY"

        rm "$full_result_path"
      shell: bash
