name: Download

on:
  push:
    branches:
      - master

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: ./
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: upload.yml
          pr: 1
          name: artifact
          path: artifact
      - name: Test
        run: |
          grep branding artifact/action.yml
