name: Bump packages
description: Bump (update) Homebrew outdated packages
author: SMillerDev
branding:
  icon: arrow-up-circle
  color: yellow
inputs:
  token:
    description: GitHub token (not the default one)
    required: true
  formulae:
    description: Formula names, one per line
    required: false
    default: ''
  casks:
    description: Cask names, one per line
    required: false
    default: ''
  fork:
    description: Use a fork when opening a PR
    required: false
    default: ${{ github.repository_owner != 'Homebrew' }}
runs:
  using: composite
  steps:
    - run: |
        if [[ "$INPUT_FORK" == "true" ]]; then
          brew bump --open-pr --formulae ${{ inputs.formulae }}
        else
          brew bump --no-fork --open-pr --formulae ${{ inputs.formulae }}
        fi
      shell: bash
      if: inputs.formulae != ''
      env:
        HOMEBREW_DEVELOPER: "1"
        HOMEBREW_GITHUB_API_TOKEN: ${{ inputs.token }}
    - run: |
        if [[ "$INPUT_FORK" == "true" ]]; then
          brew bump --open-pr --casks ${{ inputs.casks }}
        else
          brew bump --no-fork --open-pr --casks ${{ inputs.casks }}
        fi
      shell: bash
      if: inputs.casks != ''
      env:
        HOMEBREW_DEVELOPER: "1"
        HOMEBREW_GITHUB_API_TOKEN: ${{ inputs.token }}
