name: Ruby Homebrew script
description: Run Ruby script in Homebrew environment
author: dawidd6
branding:
  icon: code
  color: yellow
inputs:
  token:
    description: GitHub token (HOMEBREW_GITHUB_API_TOKEN)
    required: false
    default: ${{github.token}}
  script:
    description: Ruby script to execute
    required: true
runs:
  using: composite
  steps:
    - run: echo "$SCRIPT" > "/tmp/brew-script-$GITHUB_SHA"
      shell: bash
      env:
        SCRIPT: ${{inputs.script}}
    - run: brew ruby "/tmp/brew-script-$GITHUB_SHA"
      shell: bash
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{inputs.token}}
        HOMEBREW_NO_AUTO_UPDATE: 1
