name: setup-commit-signing
description: Set up GPG commit signing
author: nandahkrishna
branding:
  icon: user-check
  color: green
inputs:
  signing_key:
    description: Secret key to use for signing commits
    required: true
runs:
  using: composite
  steps:
    - run: |
        "$GITHUB_ACTION_PATH/main.sh" "$SIGNING_KEY"
      shell: bash
      id: setup
      env:
        SIGNING_KEY: ${{ inputs.signing_key }}
