name: Bump formulae

on:
  pull_request:
    paths:
      - "**bump-formulae**"
      - "package.json"
      - "package-lock.json"
      - "node_modules/**"

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin" >> "${GITHUB_PATH}"

      - name: Bump
        uses: ./bump-formulae/
        with:
          token: ${{github.token}}
          formulae: hello
