name: Cancel previous runs

on:
  push:
    paths:
      - '**cancel-previous-runs**'

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cancel
        uses: ./cancel-previous-runs
