name: Dismiss approvals

on:
  push:
    paths:
      - '**dismiss-approvals**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'

jobs:
  dismiss-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dismiss
        uses: ./dismiss-approvals/
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          pr: 21
          message: test
      - name: Approve
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh pr review --approve 21
