name: Download artifact

on:
  push:
    paths:
      - '**download-artifact**'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download
        uses: ./download-artifact/
        with:
          workflow: download-artifact-upload.yml
          name: artifact
          path: artifact
      - name: Test
        run: |
          ls artifact/workflows/*.yml
