name: Download artifact

on:
  push:
    paths:
      - '**download-artifact**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./.github
