name: Setup Homebrew

on:
  push:
    paths:
      - '**setup-homebrew**'
      - 'package.json'
      - 'package-lock.json'
      - 'node_modules/**'

jobs:
  setup:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check syntax
        run: bash -n setup-homebrew/*.sh
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: ./setup-homebrew/
      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@master
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-
      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems
      - name: Run brew test-bot --only-cleanup-before
        run: brew test-bot --only-cleanup-before
      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup
      - name: Run brew test-bot --only-tap-syntax
        run: brew test-bot --only-tap-syntax
