name: Node test

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run tests
        run: npm test -- --experimental-test-coverage --test-reporter lcov --test-reporter-destination lcov.info

      - name: Upload coverage results
        uses: codecov/codecov-action@968872560f81e7bdde9272853e65f2507c0eca7c # v5.0.0
        with:
          files: lcov.info
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
